# Generated by Django 5.2.7 on 2025-10-27 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL-идентификатор')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('specifications_text', models.TextField(blank=True, verbose_name='Характеристики (текст)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('delivery_time', models.CharField(default='1-3 дня', max_length=50, verbose_name='Время доставки')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='Гарантия (месяцев)')),
                ('is_official_warranty', models.BooleanField(default=True, verbose_name='Официальная гарантия')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Продажи')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Со скидкой')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('value_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('list', 'Список')], default='text', max_length=20, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=200, verbose_name='Текстовое значение')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Числовое значение')),
                ('value_boolean', models.BooleanField(default=False, verbose_name='Булево значение')),
                ('value_list', models.CharField(blank=True, max_length=200, verbose_name='Значение из списка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productspecification')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'ordering': ['specification__sort_order', 'specification__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('daily_views', models.PositiveIntegerField(default=0, verbose_name='Просмотров сегодня')),
                ('weekly_views', models.PositiveIntegerField(default=0, verbose_name='Просмотров за неделю')),
                ('monthly_views', models.PositiveIntegerField(default=0, verbose_name='Просмотров за месяц')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Всего продаж')),
                ('daily_sales', models.PositiveIntegerField(default=0, verbose_name='Продаж сегодня')),
                ('weekly_sales', models.PositiveIntegerField(default=0, verbose_name='Продаж за неделю')),
                ('monthly_sales', models.PositiveIntegerField(default=0, verbose_name='Продаж за месяц')),
                ('wishlist_count', models.PositiveIntegerField(default=0, verbose_name='В избранном')),
                ('compare_count', models.PositiveIntegerField(default=0, verbose_name='В сравнении')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Статистика товара',
                'verbose_name_plural': 'Статистика товаров',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Рейтинг')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pros', models.TextField(blank=True, verbose_name='Достоинства')),
                ('cons', models.TextField(blank=True, verbose_name='Недостатки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Проверенная покупка')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Полезно')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='Не полезно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='Полезен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за полезность',
                'verbose_name_plural': 'Голоса за полезность',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='catalog_pro_categor_a6606d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='catalog_pro_is_acti_e6e001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='productspecificationvalue',
            unique_together={('product', 'specification')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
    ]
