# Generated by Django 5.2.7 on 2025-10-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCartAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('clear', 'Очистка'), ('apply_discount', 'Применение скидки'), ('set_delivery', 'Установка доставки'), ('export', 'Экспорт')], max_length=20, verbose_name='Тип действия')),
                ('action_data', models.JSONField(verbose_name='Данные действия')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_cart_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Массовая операция',
                'verbose_name_plural': 'Массовые операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='ID сессии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Количество товаров')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Общее количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая скидка')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая стоимость')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Размер скидки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Порог бесплатной доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('applied_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='accounts.discountcode', verbose_name='Примененная скидка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abandonment_reason', models.CharField(blank=True, max_length=100, verbose_name='Причина отказа')),
                ('abandoned_at', models.DateTimeField(auto_now_add=True, verbose_name='Покинута')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('recovery_sent', models.BooleanField(default=False, verbose_name='Отправлено письмо возврата')),
                ('recovery_opened', models.BooleanField(default=False, verbose_name='Открыто письмо возврата')),
                ('recovered', models.BooleanField(default=False, verbose_name='Восстановлена')),
                ('recovered_at', models.DateTimeField(blank=True, null=True, verbose_name='Восстановлена')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandonment', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Покинутая корзина',
                'verbose_name_plural': 'Покинутые корзины',
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='CartAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='ID сессии')),
                ('cart_data', models.JSONField(verbose_name='Данные корзины')),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость корзины')),
                ('items_count', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('conversion_stage', models.CharField(choices=[('viewed', 'Просмотрена'), ('added_item', 'Добавлен товар'), ('started_checkout', 'Начато оформление'), ('completed_checkout', 'Завершено оформление'), ('abandoned', 'Покинута')], max_length=50, verbose_name='Этап конверсии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аналитика корзины',
                'verbose_name_plural': 'Аналитика корзин',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='ID сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Сессия корзины',
                'verbose_name_plural': 'Сессии корзин',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('old_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Размер скидки')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('product_sku', models.CharField(max_length=50, verbose_name='Артикул')),
                ('product_brand', models.CharField(default='', max_length=100, verbose_name='Бренд')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['-added_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='Просмотрен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recently_viewed', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Недавно просмотренный',
                'verbose_name_plural': 'Недавно просмотренные',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_saved', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отложенный товар',
                'verbose_name_plural': 'Отложенные товары',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
