# Generated by Django 5.2.7 on 2025-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код скидки'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки (старое поле)'),
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Подытог'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Налог'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма (старое поле)'),
        ),
        migrations.AddField(
            model_name='cart',
            name='used_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано бонусных баллов'),
        ),
    ]
